---
title: "Fully Dark-Adapted Fv/Fm Analysis"
subtitle: "From measurements taken by a Walz Diving PAMII"
author: "Sarah Tanja"
date: "`r format(Sys.time(), '%d %B, %Y')`"  
format:
  html:
    df-print: paged
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: breeze
    code-overflow: wrap
    theme: minty
editor: 
  markdown: 
    wrap: 72
---

# Install and load packages

```{r}
# Install packages
if ("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse')
if ("dplyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('dplyr')
if ("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate')
if ("stringr" %in% rownames(installed.packages()) == 'FALSE') install.packages('stringr')

# Load packages
library(dplyr)
library(tidyverse)
library(lubridate)
library(stringr)
```

# Pull in data

This data is generated by the report tab in the Win-3 Control Software of the Walz Diving PAM II. The metadata was added to it manually in excel, rather than creating a separate spreadsheet. 

```{r}
fvfm_0619 <- read_csv("data/fvfm_06192024.csv")
fvfm_0620 <- read_csv("data/fvfm_06202024.csv")
fvfm_0621 <- read_csv("data/fvfm_06212024.csv")
fvfm_0622 <- read_csv("data/fvfm_06222024.csv")
```

# Join data into time-series

```{r}
fvfm <- merge(fvfm_0619, fvfm_0620) %>% 
  merge(fvfm_0621) %>% 
  merge(fvfm_0622)
```

